"use strict";

class IndustrialZone extends Level {
  build() {
    this.name = "The Industrial Zone";
    this.tint = new THREE.Color(0.7, 0.4, 0.1);
    this.skyHigh = 0.15;
    this.skyLow = 1.0;
    this.skyGradient = 0.25;
    this.ground = 0.05;
    var whiteLinesColor = 0.6;
    var lightColor = 1.0;
    var industrialTallThingAPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialTallThingAPath, 300, 0.5, RoadLineStyle.DOT(250), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingAPath, 320, 0.75, RoadLineStyle.DOT(250), 0, 1, 1);
    var industrialTallThingAMesh = makeMesh(industrialTallThingAPath, 2, 10, lightColor);
    industrialTallThingAMesh.position.z = 60;
    this.meshes.push(industrialTallThingAMesh);
    var industrialTallThingBPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 300, 0.5, RoadLineStyle.DOT(250), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 320, 0.75, RoadLineStyle.DOT(250), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 400, 8, RoadLineStyle.DOT(240), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 500, 8, RoadLineStyle.DOT(240), 0, 1, 1);
    var industrialTallThingBMesh = makeMesh(industrialTallThingBPath, 60, 10, this.ground);
    this.meshes.push(industrialTallThingBMesh);
    var industrialMediumThingsPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath,-80, 20, RoadLineStyle.DASH(40, 60), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 180, 50, RoadLineStyle.DASH(40, 30), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 300, 50, RoadLineStyle.DASH(20, 20), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath,-100, 8, RoadLineStyle.DOT(200), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath,-60, 8, RoadLineStyle.DOT(1500), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 100, 8, RoadLineStyle.DOT(140), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 120, 8, RoadLineStyle.DOT(220), 0, 1, 1);
    var industrialMediumThingsMesh = makeMesh(industrialMediumThingsPath, 12, 10, this.ground);
    this.meshes.push(industrialMediumThingsMesh);
    var industrialWhiteLinesPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath,-3.5, 0.15, RoadLineStyle.DASH(60, 2), 0, 1, 1000);
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath, 3.5, 0.15, RoadLineStyle.DASH(60, 2), 0, 1, 1000);
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath,-0.15, 0.125, RoadLineStyle.DASH(4, 6), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath, 0.125, 0.125, RoadLineStyle.SOLID, 0, 1, 1000);
    var industrialWhiteLinesMesh = makeMesh(industrialWhiteLinesPath, 0, 10, whiteLinesColor);
    this.meshes.push(industrialWhiteLinesMesh);
    var industrialCrossingPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialCrossingPath, 0, 1, RoadLineStyle.DASH(2, 200), 0, 1, 1);
    var industrialCrossingMesh = makeMesh(industrialCrossingPath, 0, 10, this.ground);
    industrialCrossingMesh.position.z = 0.001;
    this.meshes.push(industrialCrossingMesh);
    var industrialCrossingLinesPath = new THREE.ShapePath();
    var _g = 0;
    while (_g < 6) {
      var i = _g++;
      var width = 0.5;
      this.drawRoadLine(this.roadPath, industrialCrossingLinesPath, i * 2 * width - 3 + width, width, RoadLineStyle.DASH(2, 200), 0, 1, 1);
    }
    var industrialCrossingLinesMesh = makeMesh(industrialCrossingLinesPath, 0, 10, whiteLinesColor);
    industrialCrossingLinesMesh.position.z = 0.01;
    this.meshes.push(industrialCrossingLinesMesh);
    var left = 80;
    var right = 80;
    var thick = 0.2;
    var tall = 15;
    var industrialStreetLight1Path = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialStreetLight1Path,-5.6, 5, RoadLineStyle.DASH(thick, left), 0, 1, 1);
    var industrialStreetLight1Mesh = makeMesh(industrialStreetLight1Path, thick, 10, this.ground);
    industrialStreetLight1Mesh.position.z = tall + thick;
    this.meshes.push(industrialStreetLight1Mesh);
    var industrialStreetLight2Path = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialStreetLight2Path,-8, thick, RoadLineStyle.DASH(thick, left), 0, 1, 1);
    var industrialStreetLight2Mesh = makeMesh(industrialStreetLight2Path, tall + thick, 10, this.ground);
    this.meshes.push(industrialStreetLight2Mesh);
    var industrialStreetLight3Path = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialStreetLight3Path,-4, 2, RoadLineStyle.DASH(thick, left), 0, 1, 1);
    var industrialStreetLight3Mesh = makeMesh(industrialStreetLight3Path, thick * 2, 10, lightColor);
    industrialStreetLight3Mesh.position.z = tall - thick;
    this.meshes.push(industrialStreetLight3Mesh);
    var depth = 8;
    var spacing = 300;
    var highwayAbove = this.roadPath.clone();
    highwayAbove.scale(1, 1.5);
    var industrialOverpassAPath = new THREE.ShapePath();
    this.drawRoadLine(highwayAbove, industrialOverpassAPath, 0, 162, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    var industrialOverpassAMesh = makeMesh(industrialOverpassAPath, 2, 10, this.ground);
    industrialOverpassAMesh.position.z = 10;
    industrialOverpassAMesh.scale.set(1, 0.66666666666666663, 1);
    this.meshes.push(industrialOverpassAMesh);
    var industrialOverpassBPath = new THREE.ShapePath();
    this.drawRoadLine(highwayAbove, industrialOverpassBPath,-100, 42, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath,-40, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath,-15, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath, 15, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath, 40, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath, 200, 242, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    var industrialOverpassBMesh = makeMesh(industrialOverpassBPath, 10, 10, this.ground);
    industrialOverpassBMesh.scale.set(1, 0.66666666666666663, 1);
    this.meshes.push(industrialOverpassBMesh);
    var industrialPolesPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialPolesPath,-30, 0.25, RoadLineStyle.DOT(90), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath,-40, 0.25, RoadLineStyle.DOT(110), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 60, 0.25, RoadLineStyle.DOT(60), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath,-50, 0.25, RoadLineStyle.DOT(60), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath,-20, 0.125, RoadLineStyle.DOT(100), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 20, 0.25, RoadLineStyle.DOT(45), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 50, 0.125, RoadLineStyle.DOT(50), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 70, 0.25, RoadLineStyle.DOT(75), 0, 1, 1);
    var industrialPolesMesh = makeMesh(industrialPolesPath, 12, 10, this.ground);
    this.meshes.push(industrialPolesMesh);
    var industrialKnobsPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialKnobsPath,-40, 1, RoadLineStyle.DOT(110), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialKnobsPath, 60, 1, RoadLineStyle.DOT(60), 0, 1, 1);
    var industrialKnobsMesh = makeMesh(industrialKnobsPath, 1, 10, this.ground);
    industrialKnobsMesh.position.z = 12;
    this.meshes.push(industrialKnobsMesh);
    var wireThickness = 0.075;
    var industrialWiresPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialWiresPath,-50, wireThickness, RoadLineStyle.DASH(60, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath,-20, wireThickness, RoadLineStyle.DASH(100, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath, 20, wireThickness, RoadLineStyle.DASH(45, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath, 50, wireThickness, RoadLineStyle.DASH(50, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath, 70, wireThickness, RoadLineStyle.DASH(75, 0), 0, 1, 1);
    var industrialWiresMesh = makeMesh(industrialWiresPath, wireThickness, 10, this.ground);
    industrialWiresMesh.position.z = 11.25;
    this.meshes.push(industrialWiresMesh);
    var tall1 = 5;
    var spacing1 = 30;
    var dist = 25;
    var industrialFenceAPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialFenceAPath,-dist, 0.1, RoadLineStyle.DOT(spacing1), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialFenceAPath, dist, 0.1, RoadLineStyle.DOT(spacing1), 0, 1, 1);
    var industrialFenceAMesh = makeMesh(industrialFenceAPath, tall1, 10, this.ground);
    this.meshes.push(industrialFenceAMesh);
    var industrialFenceBPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialFenceBPath,-dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialFenceBPath, dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    var industrialFenceBMesh = makeMesh(industrialFenceBPath, 0.1, 10, this.ground);
    industrialFenceBMesh.position.z = tall1 - 0.5;
    this.meshes.push(industrialFenceBMesh);
    var industrialFenceCPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialFenceCPath,-dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialFenceCPath, dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    var industrialFenceCMesh = makeMesh(industrialFenceCPath, tall1 - 0.5, 10, this.ground, 0.25);
    this.meshes.push(industrialFenceCMesh);
  }
}
