"use strict";

class IndustrialZone extends Level {
  build() {
    this.name = "The Industrial Zone";
    this.tint = new THREE.Color(0.7, 0.4, 0.1);
    this.skyHigh = 0.15;
    this.skyLow = 1.0;
    this.skyGradient = 0.25;
    this.ground = 0.05;
    const whiteLinesColor = 0.6;
    const lightColor = 1.0;
    const industrialTallThingAPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialTallThingAPath, 300, 0.5, RoadLineStyle.DOT(250), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingAPath, 320, 0.75, RoadLineStyle.DOT(250), 0, 1, 1);
    const industrialTallThingAMesh = makeMesh(industrialTallThingAPath, 2, 10, lightColor);
    industrialTallThingAMesh.position.z = 60;
    this.meshes.push(industrialTallThingAMesh);
    const industrialTallThingBPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 300, 0.5, RoadLineStyle.DOT(250), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 320, 0.75, RoadLineStyle.DOT(250), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 400, 8, RoadLineStyle.DOT(240), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialTallThingBPath, 500, 8, RoadLineStyle.DOT(240), 0, 1, 1);
    const industrialTallThingBMesh = makeMesh(industrialTallThingBPath, 60, 10, this.ground);
    this.meshes.push(industrialTallThingBMesh);
    const industrialMediumThingsPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath,-80, 20, RoadLineStyle.DASH(40, 60), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 180, 50, RoadLineStyle.DASH(40, 30), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 300, 50, RoadLineStyle.DASH(20, 20), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath,-100, 8, RoadLineStyle.DOT(200), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath,-60, 8, RoadLineStyle.DOT(1500), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 100, 8, RoadLineStyle.DOT(140), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialMediumThingsPath, 120, 8, RoadLineStyle.DOT(220), 0, 1, 1);
    const industrialMediumThingsMesh = makeMesh(industrialMediumThingsPath, 12, 10, this.ground);
    this.meshes.push(industrialMediumThingsMesh);
    const industrialWhiteLinesPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath,-3.5, 0.15, RoadLineStyle.DASH(60, 2), 0, 1, 1000);
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath, 3.5, 0.15, RoadLineStyle.DASH(60, 2), 0, 1, 1000);
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath,-0.15, 0.125, RoadLineStyle.DASH(4, 6), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWhiteLinesPath, 0.125, 0.125, RoadLineStyle.SOLID(), 0, 1, 1000);
    const industrialWhiteLinesMesh = makeMesh(industrialWhiteLinesPath, 0, 10, whiteLinesColor);
    this.meshes.push(industrialWhiteLinesMesh);
    const industrialCrossingPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialCrossingPath, 0, 1, RoadLineStyle.DASH(2, 200), 0, 1, 1);
    const industrialCrossingMesh = makeMesh(industrialCrossingPath, 0, 10, this.ground);
    industrialCrossingMesh.position.z = 0.001;
    this.meshes.push(industrialCrossingMesh);
    const industrialCrossingLinesPath = new THREE.ShapePath();
    for (let i = 0; i < 6; i++) {
        const width = 6.0 / 6 * 0.5;
        this.drawRoadLine(this.roadPath, industrialCrossingLinesPath, i * 2 * width - 3 + width, width, RoadLineStyle.DASH(2, 200), 0, 1, 1);
    }
    const industrialCrossingLinesMesh = makeMesh(industrialCrossingLinesPath, 0, 10, whiteLinesColor);
    industrialCrossingLinesMesh.position.z = 0.01;
    this.meshes.push(industrialCrossingLinesMesh);
    const left = 80;
    const right = 80;
    const thick = 0.2;
    const tall = 15;
    const industrialStreetLight1Path = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialStreetLight1Path,-5.6, 5, RoadLineStyle.DASH(thick, left), 0, 1, 1);
    const industrialStreetLight1Mesh = makeMesh(industrialStreetLight1Path, thick, 10, this.ground);
    industrialStreetLight1Mesh.position.z = tall + thick;
    this.meshes.push(industrialStreetLight1Mesh);
    const industrialStreetLight2Path = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialStreetLight2Path,-8, thick, RoadLineStyle.DASH(thick, left), 0, 1, 1);
    const industrialStreetLight2Mesh = makeMesh(industrialStreetLight2Path, tall + thick, 10, this.ground);
    this.meshes.push(industrialStreetLight2Mesh);
    const industrialStreetLight3Path = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialStreetLight3Path,-4, 2, RoadLineStyle.DASH(thick, left), 0, 1, 1);
    const industrialStreetLight3Mesh = makeMesh(industrialStreetLight3Path, thick * 2, 10, lightColor);
    industrialStreetLight3Mesh.position.z = tall - thick;
    this.meshes.push(industrialStreetLight3Mesh);
    const depth = 8;
    const spacing = 300;
    const highwayAbove = this.roadPath.clone();
    highwayAbove.scale(1, 1.5);
    const industrialOverpassAPath = new THREE.ShapePath();
    this.drawRoadLine(highwayAbove, industrialOverpassAPath, 0, 162, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    const industrialOverpassAMesh = makeMesh(industrialOverpassAPath, 2, 10, this.ground);
    industrialOverpassAMesh.position.z = 10;
    industrialOverpassAMesh.scale.set(1, 0.66666666666666663, 1);
    this.meshes.push(industrialOverpassAMesh);
    const industrialOverpassBPath = new THREE.ShapePath();
    this.drawRoadLine(highwayAbove, industrialOverpassBPath,-100, 42, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath,-40, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath,-15, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath, 15, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath, 40, 2, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    this.drawRoadLine(highwayAbove, industrialOverpassBPath, 200, 242, RoadLineStyle.DASH(depth, spacing), 0, 1, 1);
    const industrialOverpassBMesh = makeMesh(industrialOverpassBPath, 10, 10, this.ground);
    industrialOverpassBMesh.scale.set(1, 0.66666666666666663, 1);
    this.meshes.push(industrialOverpassBMesh);
    const industrialPolesPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialPolesPath,-30, 0.25, RoadLineStyle.DOT(90), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath,-40, 0.25, RoadLineStyle.DOT(110), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 60, 0.25, RoadLineStyle.DOT(60), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath,-50, 0.25, RoadLineStyle.DOT(60), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath,-20, 0.125, RoadLineStyle.DOT(100), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 20, 0.25, RoadLineStyle.DOT(45), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 50, 0.125, RoadLineStyle.DOT(50), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialPolesPath, 70, 0.25, RoadLineStyle.DOT(75), 0, 1, 1);
    const industrialPolesMesh = makeMesh(industrialPolesPath, 12, 10, this.ground);
    this.meshes.push(industrialPolesMesh);
    const industrialKnobsPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialKnobsPath,-40, 1, RoadLineStyle.DOT(110), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialKnobsPath, 60, 1, RoadLineStyle.DOT(60), 0, 1, 1);
    const industrialKnobsMesh = makeMesh(industrialKnobsPath, 1, 10, this.ground);
    industrialKnobsMesh.position.z = 12;
    this.meshes.push(industrialKnobsMesh);
    const wireThickness = 0.075;
    const industrialWiresPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialWiresPath,-50, wireThickness, RoadLineStyle.DASH(60, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath,-20, wireThickness, RoadLineStyle.DASH(100, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath, 20, wireThickness, RoadLineStyle.DASH(45, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath, 50, wireThickness, RoadLineStyle.DASH(50, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialWiresPath, 70, wireThickness, RoadLineStyle.DASH(75, 0), 0, 1, 1);
    const industrialWiresMesh = makeMesh(industrialWiresPath, wireThickness, 10, this.ground);
    industrialWiresMesh.position.z = 11.25;
    this.meshes.push(industrialWiresMesh);
    const tall1 = 5;
    const spacing1 = 30;
    const dist = 25;
    const industrialFenceAPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialFenceAPath,-dist, 0.1, RoadLineStyle.DOT(spacing1), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialFenceAPath, dist, 0.1, RoadLineStyle.DOT(spacing1), 0, 1, 1);
    const industrialFenceAMesh = makeMesh(industrialFenceAPath, tall1, 10, this.ground);
    this.meshes.push(industrialFenceAMesh);
    const industrialFenceBPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialFenceBPath,-dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialFenceBPath, dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    const industrialFenceBMesh = makeMesh(industrialFenceBPath, 0.1, 10, this.ground);
    industrialFenceBMesh.position.z = tall1 - 0.5;
    this.meshes.push(industrialFenceBMesh);
    const industrialFenceCPath = new THREE.ShapePath();
    this.drawRoadLine(this.roadPath, industrialFenceCPath,-dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    this.drawRoadLine(this.roadPath, industrialFenceCPath, dist, 0.1, RoadLineStyle.DASH(spacing1, 0), 0, 1, 1);
    const industrialFenceCMesh = makeMesh(industrialFenceCPath, tall1 - 0.5, 10, this.ground, 0.25);
    this.meshes.push(industrialFenceCMesh);
  }
}
